#!/usr/bin/env python3

import os
import sys
from PySide import QtCore, QtGui

class fMain(QtGui.QDialog):
    def __init__(self, parent = None):
        QtGui.QDialog.__init__(self, parent)
        self.setupUi(self)
    
    def setupUi(self, fMain):
        fMain.setObjectName("fMain")
        fMain.setWindowModality(QtCore.Qt.ApplicationModal)
        fMain.resize(766, 430)
        self.verticalLayout_10 = QtGui.QVBoxLayout(fMain)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.fraInputs = QtGui.QGroupBox(fMain)
        self.fraInputs.setObjectName("fraInputs")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.fraInputs)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lblDetail = QtGui.QLabel(self.fraInputs)
        self.lblDetail.setObjectName("lblDetail")
        self.verticalLayout_6.addWidget(self.lblDetail)
        self.pnlPolyPx = QtGui.QFrame(self.fraInputs)
        self.pnlPolyPx.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pnlPolyPx.setFrameShadow(QtGui.QFrame.Raised)
        self.pnlPolyPx.setObjectName("pnlPolyPx")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.pnlPolyPx)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblPolyPx = QtGui.QLabel(self.pnlPolyPx)
        self.lblPolyPx.setObjectName("lblPolyPx")
        self.horizontalLayout.addWidget(self.lblPolyPx)
        self.txtPolyPx = QtGui.QLineEdit(self.pnlPolyPx)
        self.txtPolyPx.setObjectName("txtPolyPx")
        self.horizontalLayout.addWidget(self.txtPolyPx)
        self.cmdLoadPolyPx = QtGui.QPushButton(self.pnlPolyPx)
        self.cmdLoadPolyPx.setAutoDefault(False)
        self.cmdLoadPolyPx.setObjectName("cmdLoadPolyPx")
        self.horizontalLayout.addWidget(self.cmdLoadPolyPx)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.txtPolyPxFull = QtGui.QLineEdit(self.pnlPolyPx)
        self.txtPolyPxFull.setReadOnly(True)
        self.txtPolyPxFull.setObjectName("txtPolyPxFull")
        self.verticalLayout_2.addWidget(self.txtPolyPxFull)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addWidget(self.pnlPolyPx)
        self.pnlPolyQx = QtGui.QFrame(self.fraInputs)
        self.pnlPolyQx.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pnlPolyQx.setFrameShadow(QtGui.QFrame.Raised)
        self.pnlPolyQx.setObjectName("pnlPolyQx")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.pnlPolyQx)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblPolyQx = QtGui.QLabel(self.pnlPolyQx)
        self.lblPolyQx.setObjectName("lblPolyQx")
        self.horizontalLayout_2.addWidget(self.lblPolyQx)
        self.txtPolyQx = QtGui.QLineEdit(self.pnlPolyQx)
        self.txtPolyQx.setObjectName("txtPolyQx")
        self.horizontalLayout_2.addWidget(self.txtPolyQx)
        self.cmdLoadPolyQx = QtGui.QPushButton(self.pnlPolyQx)
        self.cmdLoadPolyQx.setAutoDefault(False)
        self.cmdLoadPolyQx.setObjectName("cmdLoadPolyQx")
        self.horizontalLayout_2.addWidget(self.cmdLoadPolyQx)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.txtPolyQxFull = QtGui.QLineEdit(self.pnlPolyQx)
        self.txtPolyQxFull.setReadOnly(True)
        self.txtPolyQxFull.setObjectName("txtPolyQxFull")
        self.verticalLayout_3.addWidget(self.txtPolyQxFull)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addWidget(self.pnlPolyQx)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.lblDetail2 = QtGui.QLabel(self.fraInputs)
        self.lblDetail2.setObjectName("lblDetail2")
        self.verticalLayout_6.addWidget(self.lblDetail2)
        self.pnlMethods = QtGui.QFrame(self.fraInputs)
        self.pnlMethods.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pnlMethods.setFrameShadow(QtGui.QFrame.Raised)
        self.pnlMethods.setObjectName("pnlMethods")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.pnlMethods)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chkMethod1 = QtGui.QCheckBox(self.pnlMethods)
        self.chkMethod1.setObjectName("chkMethod1")
        self.horizontalLayout_3.addWidget(self.chkMethod1)
        self.chkMethod2 = QtGui.QCheckBox(self.pnlMethods)
        self.chkMethod2.setObjectName("chkMethod2")
        self.horizontalLayout_3.addWidget(self.chkMethod2)
        self.chkMethod3 = QtGui.QCheckBox(self.pnlMethods)
        self.chkMethod3.setObjectName("chkMethod3")
        self.horizontalLayout_3.addWidget(self.chkMethod3)
        self.chkMethod4 = QtGui.QCheckBox(self.pnlMethods)
        self.chkMethod4.setObjectName("chkMethod4")
        self.horizontalLayout_3.addWidget(self.chkMethod4)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.cmdMultiply = QtGui.QPushButton(self.pnlMethods)
        self.cmdMultiply.setAutoDefault(False)
        self.cmdMultiply.setDefault(True)
        self.cmdMultiply.setObjectName("cmdMultiply")
        self.horizontalLayout_3.addWidget(self.cmdMultiply)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addWidget(self.pnlMethods)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout.addWidget(self.fraInputs)
        self.fraResults = QtGui.QGroupBox(fMain)
        self.fraResults.setObjectName("fraResults")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.fraResults)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblPolyRx = QtGui.QLabel(self.fraResults)
        self.lblPolyRx.setObjectName("lblPolyRx")
        self.horizontalLayout_5.addWidget(self.lblPolyRx)
        self.txtPolyRx = QtGui.QLineEdit(self.fraResults)
        self.txtPolyRx.setReadOnly(True)
        self.txtPolyRx.setObjectName("txtPolyRx")
        self.horizontalLayout_5.addWidget(self.txtPolyRx)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout.addWidget(self.fraResults)
        self.verticalLayout_10.addLayout(self.verticalLayout)

        self.retranslateUi(fMain)
        QtCore.QMetaObject.connectSlotsByName(fMain)

    def retranslateUi(self, fMain):
        fMain.setWindowTitle(QtGui.QApplication.translate("fMain", "Multiplication of polynomials", None, QtGui.QApplication.UnicodeUTF8))
        self.fraInputs.setTitle(QtGui.QApplication.translate("fMain", "Inputs", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDetail.setText(QtGui.QApplication.translate("fMain", "Enter two polynomials:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPolyPx.setText(QtGui.QApplication.translate("fMain", "P(x) =", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdLoadPolyPx.setText(QtGui.QApplication.translate("fMain", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPolyQx.setText(QtGui.QApplication.translate("fMain", "Q(x) =", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdLoadPolyQx.setText(QtGui.QApplication.translate("fMain", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDetail2.setText(QtGui.QApplication.translate("fMain", "Select method(s):", None, QtGui.QApplication.UnicodeUTF8))
        self.chkMethod1.setText(QtGui.QApplication.translate("fMain", "Method1", None, QtGui.QApplication.UnicodeUTF8))
        self.chkMethod2.setText(QtGui.QApplication.translate("fMain", "Method2", None, QtGui.QApplication.UnicodeUTF8))
        self.chkMethod3.setText(QtGui.QApplication.translate("fMain", "Method3", None, QtGui.QApplication.UnicodeUTF8))
        self.chkMethod4.setText(QtGui.QApplication.translate("fMain", "Method4", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdMultiply.setText(QtGui.QApplication.translate("fMain", "Multiply", None, QtGui.QApplication.UnicodeUTF8))
        self.fraResults.setTitle(QtGui.QApplication.translate("fMain", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPolyRx.setText(QtGui.QApplication.translate("fMain", "R(x) =", None, QtGui.QApplication.UnicodeUTF8))

def main():
    app = QtGui.QApplication(sys.argv)
    f = fMain()

    r = f.geometry()
    r.moveCenter(app.desktop().availableGeometry().center())
    f.setGeometry(r)

    f.show()
    sys.exit(app.exec_())

if __name__ == '__main__':
    main()
